---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certalert-config
data:
  certalert.yaml: |
    certalert:
      check-interval: 30m
      certificates:
        - name: MyApp Keystore
          path: /certs/myapp.jks
          type: jks
          password: file:/passwords/certificates.passwords//jks_password
        - name: MyApp P12
          path: /certs/myapp.p12
          type: pkcs12
          password: changeit
