---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certalert-config
data:
  config.yaml: |
    certalert:
      check-inverval: 30m
      certificates:
        - name: MyApp Keystore
          path: myapp.jks
          type: pkcs12
          password: file:/password/certificates.passwords//jks_password
        - name: MyApp P12
          path: myapp.p12
          type: pkcs12
          password: changeit