---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certalert
spec:
  selector:
    matchLabels:
      app: certalert
  template:
    metadata:
      labels:
        app: certalert
    spec:
      containers:
        - name: certalert
          image: ghcr.io/thurgauerkb/certalert:latest
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
            - name: password-file
              mountPath: /passwords
            - name: certs
              mountPath: /certs
          resources: { }
      volumes:
        - name: config
          configMap:
            name: certalert-config
        - name: certs
          configMap:
            name: certificates
        - name: passwords-file
          secret:
            secretName: password-file