{
 "title": "certalert V2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Extraction Certificates (Total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(certalert_certificate_validity[$__range]))"
    }
   ]
  },
  {
   "title": "Extraction Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(certalert_certificate_validity[$__range]) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extraction Errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(certalert_certificate_validity[$__range]) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(certalert_certificate_expiration_seconds[$__range]) -time()",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}