name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build:
    needs: tests
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

        # Java / Gradle cache
      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build application JAR
        run: ./gradlew bootJar -x test --no-daemon

      - name: Determine version (from tag)
        id: tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Upload JAR artifact (for release workflow)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/*.jar

      - name: Log in to GitHub Container registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          labels: |
            org.opencontainers.image.title=certalert
            org.opencontainers.image.description=certalert
            org.opencontainers.image.url=https://github.com/gi8lino/certalert
            org.opencontainers.image.source=https://github.com/gi8lino/certalert
            org.opencontainers.image.version=${{ steps.tag.outputs.version }}
          tags: |
            ghcr.io/gi8lino/certalert:${{ steps.tag.outputs.version }}
            ghcr.io/gi8lino/certalert:latest

  release:
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.build.outputs.version }}
