name: Release

on:
  workflow_call:
    inputs:
      version:
        description: "Version without the leading v (e.g. 1.2.3)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR artifact from caller
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: dist/

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.version }}
        run: |
          # Create (idempotent) release; if it already exists, this exits non-zero, so guard it.
          if gh release view "v${VERSION}" >/dev/null 2>&1; then
            echo "Release v${VERSION} already exists. Uploading assets..."
          else
            gh release create "v${VERSION}" \
              --title "certalert v${VERSION}" \
              --generate-notes \
              --latest
          fi
          gh release upload "v${VERSION}" dist/*.jar --clobber
